#!/usr/bin/env bash
# install and configure nginx on a remote ubuntu server

sudo su<<EOF

apt-get update
apt-get install -y nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" | tee /var/www/html/index.html
EOF
