#!/usr/bin/env bash
# Configures your Nginx server so that /redirect_me is redirecting to another page.

apt-get update
apt-get install -y nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "hello world" > /etc/nginx/html/index.html
echo "Ceci n'est pas une page" > /etc/nginx/html/error.html

echo 'server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    error_page 404 /error.html;
    location /error.html {
    	root /etc/nginx/html;
    	internal;
    }
}' > /etc/nginx/sites-available/default

service nginx restart
