#!/usr/bin/env bash
# install and configure nginx on a remote ubuntu server

sudo su<<EOF

apt-get update
apt-get install -y nginx
echo 'Hello World!' | tee /var/www/html/index.html
systemctl start nginx
EOF
