#!/usr/bin/env bash
# Configures Nginx to set a custom HTTP response header
apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
sed -i "/server_name _;/a \	add_header X-Served-By \"$HOSTNAME\";" /etc/nginx/sites-available/default
service nginx start
