#!/usr/bin/env bash
# Configures HAproxy on the lb-01 server.
apt-get update
apt-get install haproxy
echo 'frontend http_front
    bind *:80
    default_backend http_back
    
    backend http_back
    balance roundrobin
    server 511061-web-01 100.25.193.96:80 check
    server 511061-web-02 100.26.169.112:80 check' > /etc/haproxy/haproxy.cfg


service haproxy start
