#!/usr/bin/env bash
# This script displays To infinity and beyond indefinitely and handle signals.

trap "echo I am invincible!!!" SIGTERM

while true; do
	echo "To infinity nad beyond"
	sleep 2
done
